
sites = [
    ["YouTube", "https://www.youtube.com/"],
    ["Google", "https://www.google.com/"],
    ["Facebook", "https://www.facebook.com/"],
    ["Twitter", "https://twitter.com/"],
    ["Instagram", "https://www.instagram.com/"],
    ["Reddit", "https://www.reddit.com/"],
    ["Amazon", "https://www.amazon.com/"],
    ["Wikipedia", "https://www.wikipedia.org/"],
    ["Netflix", "https://www.netflix.com/browse"],
    ["LinkedIn", "https://www.linkedin.com/"],
    ["GitHub", "https://github.com/"],
    ["Stack Overflow", "https://stackoverflow.com/"],
    ["The New York Times", "https://www.nytimes.com/"],
    ["Apple", "https://www.apple.com/"],
    ["Microsoft", "https://www.microsoft.com/"],
    ["Amazon India", "https://www.amazon.in/"],
    ["BBC", "https://www.bbc.com/"],
    ["CNN", "https://www.cnn.com/"],
    ["Ebay", "https://www.ebay.com/"],
    ["Adobe", "https://www.adobe.com/"],
    ["CNN", "https://www.cnn.com/"],
    ["IMDb", "https://www.imdb.com/"],
    ["Alibaba", "https://www.alibaba.com/"],
    ["Baidu", "https://www.baidu.com/"],
    ["Yahoo", "https://www.yahoo.com/"],
    ["Instagram", "https://www.instagram.com/"],
    ["WhatsApp", "https://www.whatsapp.com/"],
    ["Zoom", "https://www.zoom.us/"],
    ["Pinterest", "https://www.pinterest.com/"],
    ["Snapchat", "https://www.snapchat.com/"],
    ["Spotify", "https://www.spotify.com/"],
    ["PayPal", "https://www.paypal.com/"],
    ["BBC", "https://www.bbc.com/"],
    ["BBC News", "https://www.bbc.co.uk/news"],
    ["Microsoft", "https://www.microsoft.com/"],
    ["MSN", "https://www.msn.com/"],
    ["Fox News", "https://www.foxnews.com/"],
    ["The Guardian", "https://www.theguardian.com/"],
    ["Etsy", "https://www.etsy.com/"],
    ["TripAdvisor", "https://www.tripadvisor.com/"],
    ["Home Depot", "https://www.homedepot.com/"],
    ["Target", "https://www.target.com/"],
    ["Best Buy", "https://www.bestbuy.com/"],
    ["IKEA", "https://www.ikea.com/"],
    ["Walmart", "https://www.walmart.com/"],
    ["Zillow", "https://www.zillow.com/"],
    ["Yelp", "https://www.yelp.com/"],
    ["Stack Exchange", "https://stackexchange.com/"],
    ["Quora", "https://www.quora.com/"],
    ["Reddit", "https://www.reddit.com/"],
    ["DuckDuckGo", "https://duckduckgo.com/"],
    ["Twitch", "https://www.twitch.tv/"],
    ["Discord", "https://discord.com/"],
    ["WhatsApp", "https://www.whatsapp.com/"],
    ["Alibaba", "https://www.alibaba.com/"],
    ["Booking.com", "https://www.booking.com/"],
    ["Expedia", "https://www.expedia.com/"],
    ["Airbnb", "https://www.airbnb.com/"],
    ["Wikipedia", "https://www.wikipedia.org/"],
    ["Stack Overflow", "https://stackoverflow.com/"],
    ["GitHub", "https://github.com/"],
    ["Medium", "https://medium.com/"],
    ["BuzzFeed", "https://www.buzzfeed.com/"],
    ["TechCrunch", "https://techcrunch.com/"],
    ["Mashable", "https://mashable.com/"],
    ["Gizmodo", "https://gizmodo.com/"],
    ["Engadget", "https://www.engadget.com/"],
    ["Ars Technica", "https://arstechnica.com/"],
    ["PC Gamer", "https://www.pcgamer.com/"],
    ["IGN", "https://www.ign.com/"],
    ["Polygon", "https://www.polygon.com/"],
    ["Kotaku", "https://kotaku.com/"],
    ["The Verge", "https://www.theverge.com/"],
    ["CNET", "https://www.cnet.com/"],
    ["BBC", "https://www.bbc.com/"],
    ["CNBC", "https://www.cnbc.com/"],
    ["Bloomberg", "https://www.bloomberg.com/"],
    ["Financial Times", "https://www.ft.com/"],
    ["Forbes", "https://www.forbes.com/"],
    ["Business Insider", "https://www.businessinsider.com/"],
    ["Harvard Business Review", "https://hbr.org/"],
    ["The Economist", "https://www.economist.com/"],
    ["Time", "https://time.com/"],
    ["National Geographic", "https://www.nationalgeographic.com/"],
    ["Discovery", "https://www.discovery.com/"],
    ["BBC Earth", "https://www.bbcearth.com/"],
    ["Smithsonian", "https://www.smithsonianmag.com/"],
    ["NASA", "https://www.nasa.gov/"],
    ["SpaceX", "https://www.spacex.com/"],
    ["National Science Foundation", "https://www.nsf.gov/"],
    ["World Health Organization", "https://www.who.int/"],
    ["Centers for Disease Control and Prevention", "https://www.cdc.gov/"],
    ["National Institutes of Health", "https://www.nih.gov/"],
    ["GSFC University", "https://www.gsfcuniversity.ac.in/"]
]

welcome_greetings = [
    "Welcome, sir!",
    "Hello and welcome, sir!",
    "Greetings, sir!",
    "Hi there, sir!",
    "Nice to see you, sir!",
    "Hey, welcome sir!",
    "Good to have you here, sir!",
    "Hello, sir!",
    "Welcome aboard, sir!",
    "Hi, sir!",
    "Hello, sir!",
    "Hey, sir!",
    "Hi, sir!",
    "Hello, sir!",
    "Hey, sir!",
    "Hi, sir!",
    "Hello, sir!",
    "Hey, sir!",
    "Hi, sir!",
    "Hello, sir!"
]

responses = [
    "You're welcome!",
    "No problem!",
    "My pleasure!",
    "Anytime!",
    "Glad to help!",
    "Don't mention it!",
    "No worries!",
    "Happy to assist!",
    "It was nothing!",
    "Always here for you!"
]

exit_greetings = [
    "Goodbye!",
    "See you later!",
    "Until next time!",
    "Farewell!",
    "Have a great day!",
    "Take care!",
    "Adios!",
    "Bye for now!",
    "Catch you later!",
    "So long!",
    "Until we meet again!",
    "Peace out!"
]

applications=[
    ["Vs code", "/Applications/Visual Studio Code.app"],
    ["Cycahrm", "/Applications/PyCharm CE.app"],
    ["Facetime","/System/Applications/FaceTime.app"],
    ["Games","/Applications/Combat Master.app"],
    ["Whatsapp","/Applications/WhatsApp.app"],
    ["Steam","/Applications/Steam.app"],
]

modules = [
    "numpy",
    "pandas",
    "matplotlib",
    "seaborn",
    "scikit-learn",
    "tensorflow",
    "keras",
    "torch",  # PyTorch
    "scipy",
    "opencv-python",  # OpenCV
    "requests",
    "beautifulsoup4",  # BeautifulSoup
    "flask",
    "django",
    "sqlalchemy",
    "pillow",
    "pygame",
    "nltk",
    "spacy",
    "jupyter",
    "networkx",
    "pydot",
    "plotly",
    "bokeh",
    "dash",
    "pyqt5",
    "tkinter",
    "pyaudio",
    "speechrecognition",
    "pydub",
    "gensim",
    "scrapy",
    "dash",
    "dash-bootstrap-components",
    "dash-core-components",
    "dash-html-components",
    "dash-table",
    "streamlit",
    "pyinstaller",
    "cx_freeze",
    "pygame",
    "pytest",
    "flake8",
    "black",
    "selenium",
    "pyautogui",
    "opencv-python-headless",
    "pyscreenshot",
    "pytesseract",
    "numpydoc",
    "sphinx",
    "pytest",
    "pytest-cov",
    "coverage",
    "tox",
    "virtualenv",
    "pyenv",
    "pipenv",
    "pylint",
    "autopep8",
    "pandas-profiling",
    "numpy-stl",
    "pytorch-lightning",
    "transformers",
    "huggingface-hub",
    "tqdm",
    "torchvision",
    "fastapi",
    "uvicorn",
    "starlette",
    "pytest",
    "pytest-asyncio",
    "pytest-cov",
    "pytest-sugar",
    "aiohttp",
    "databases",
    "sqlalchemy",
    "alembic",
    "tortoise-orm",
    "aiomysql",
    "aiopg",
    "asyncpg",
    "aiofiles",
    "jupyterlab",
    "jupyterlab-git",
    "jupyterlab-lsp",
    "jupyter-lsp",
    "jupyterlab-code-formatter",
    "jupyterlab-toc",
    "jupyterlab-system-monitor",
    "jupyterlab-variableInspector",
    "jupyterlab-chart-editor",
    "jupyterlab-email-sender",
    "jupyterlab-google-drive",
    "jupyterlab-plotly",
    "jupyterlab-go-to-definition",
    "jupyterlab-python-bytecode",
    "jupyterlab-topbar",
    "jupyterlab-welcome",
    "jupyterlab-widgets",
    "pyviz",
    "geopandas",
    "folium",
    "shapely",
    "fiona",
    "rasterio",
    "cartopy",
    "pyproj",
    "datashader",
    "holoviews",
    "panel",
    "bokeh",
    "altair",
    "plotly",
    "streamlit",
    "dash",
    "ipywidgets",
    "dask",
    "xarray",
    "intake",
    "pandasql",
    "sqlalchemy",
    "ibm_db_sa",
    "mysql-connector-python",
    "psycopg2",
    "pymysql",
    "pyodbc",
    "sqlalchemy-redshift",
    "sqlalchemy-bigquery",
    "elasticsearch",
    "kibana",
    "logstash",
    "Pyaudio",
    "google-cloud-bigquery",
    "google-cloud-pubsub",
    "google-cloud-spanner",
    "google-cloud-datastore",
    "google-cloud-firestore",
    "google-cloud-storage",
    "google-cloud-speech",
    "google-cloud-vision",
    "google-cloud-language",
    "google-cloud-natural-language",
    "google-cloud-texttospeech",
    "google-cloud-speech",
    "google-cloud-translate",
    "google-cloud-video-intelligence",
    "google-cloud",
    "google-api-python-client",
    "oauth2client",
    "google-auth",
    "google-auth-httplib2",
    "google-auth-oauthlib",
    "google-auth-google-auth-library",
    "openai",
    "speechrecognition",
    "gtts"
]

num=[]

for i in range(0,1001):
    num.append(i)

questions=["What", "When", "How", "Where"]
